-- ============================================================
-- BarryTech Repair Lab — Tech roster + ticket lifecycle upgrade
-- Run this in the Supabase SQL Editor (Project > SQL Editor > New query)
-- Safe to re-run: every step is additive / uses IF NOT EXISTS or drop-then-recreate.
-- ============================================================

-- 1) Tech roster table -----------------------------------------------------
create table if not exists techs (
    id bigint generated by default as identity primary key,
    name text not null,
    group_id bigint references groups(id) on delete set null,
    created_at timestamptz not null default now()
);

alter table techs enable row level security;

-- Matches the existing trust model used by groups/repair_requests/reviews:
-- the anon key is used for all reads/writes, and Admin vs Tech is gated
-- client-side after a password check (via the admin-login edge function),
-- not by Postgres roles. Re-architecting that is a good candidate for the
-- future dedicated-server rebuild, not part of this pass.
drop policy if exists "techs_select_anon" on techs;
create policy "techs_select_anon" on techs for select using (true);

drop policy if exists "techs_insert_anon" on techs;
create policy "techs_insert_anon" on techs for insert with check (true);

drop policy if exists "techs_update_anon" on techs;
create policy "techs_update_anon" on techs for update using (true);

drop policy if exists "techs_delete_anon" on techs;
create policy "techs_delete_anon" on techs for delete using (true);

-- 2) New repair_requests columns -------------------------------------------
alter table repair_requests
    add column if not exists notes text,
    add column if not exists parts_used text,
    add column if not exists created_by text default 'customer';

-- 3) Widen the status check constraint to allow 'in_progress' --------------
-- (constraint name may differ on your project; this looks it up dynamically
-- instead of hardcoding a name, so it works whether or not one already exists)
do $$
declare
    con_name text;
begin
    select con.conname into con_name
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    where rel.relname = 'repair_requests'
      and con.contype = 'c'
      and pg_get_constraintdef(con.oid) ilike '%status%';

    if con_name is not null then
        execute format('alter table repair_requests drop constraint %I', con_name);
    end if;

    alter table repair_requests
        add constraint repair_requests_status_check
        check (status in ('flagged', 'pending', 'assigned', 'in_progress', 'completed'));
end $$;
