-- ============================================================
-- BarryTech Repair Lab — tech forum: posts where students share how
-- they fixed a device (steps, YouTube links, part links), with a
-- device name, a device type and problem filters so others can search.
--   * Staff only, like tickets (008). No customer fields: a post can
--     carry a copy of a ticket's session notes, never the customer.
--   * Swear filter: a trigger refuses posts containing common swear
--     words or slurs as whole words (so "class" and "assembly" are
--     fine). Spelled-around versions get through by design.
-- Additive. Run this in the Supabase SQL Editor. Safe to re-run.
-- ============================================================

create table if not exists forum_posts (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    tech_id bigint references techs(id) on delete set null,
    author_name text not null,
    title text not null check (char_length(title) between 3 and 120),
    device text not null check (char_length(device) between 2 and 80),
    device_type text not null check (device_type in ('Laptop', 'Desktop', 'Tablet', 'Phone', 'Other')),
    tags text[] not null check (
        cardinality(tags) >= 1
        and tags <@ array['Screen', 'Battery', 'Charging', 'Keyboard', 'Storage', 'RAM', 'Software',
                          'Virus', 'Water damage', 'Overheating', 'Won''t turn on', 'Wi-Fi', 'Data recovery', 'Other']
    ),
    body text not null check (char_length(body) between 10 and 5000),
    links text[] not null default '{}' check (cardinality(links) <= 10),
    ticket_id bigint,
    ticket_notes text check (char_length(ticket_notes) <= 5000)
);

alter table forum_posts enable row level security;
drop policy if exists "forum_posts_staff_all" on forum_posts;
create policy "forum_posts_staff_all" on forum_posts
    for all using ((select is_staff())) with check ((select is_staff()));

-- Same word list as FORUM_SWEAR_PATTERN in js/main.js.
create or replace function forum_clean_check()
returns trigger
language plpgsql
as $$
begin
    if concat_ws(' ', new.title, new.device, new.body, array_to_string(new.links, ' '), new.ticket_notes)
       ~* '\m(fuck\w*|motherfuck\w*|shit\w*|bullshit\w*|bitch\w*|bastards?|assholes?|ass|dicks?|cunts?|piss(ed|ing)?|sluts?|whores?|nigg(er|a)s?|fag(got)?s?|retard(ed|s)?)\M' then
        raise exception 'Please keep it clean: remove the flagged word and try again.';
    end if;
    new.updated_at := case when tg_op = 'UPDATE' then now() else null end;
    return new;
end;
$$;

drop trigger if exists forum_clean on forum_posts;
create trigger forum_clean
    before insert or update on forum_posts
    for each row execute function forum_clean_check();

notify pgrst, 'reload schema';
